#!/bin/bash

alias -- +='pushd . >/dev/null'
alias -- -='popd >/dev/null'
alias ..='cd ..'
alias ...='cd ../..'
alias beep='echo -en "\x07"'
alias cay='cat'
alias cls='clear;echo'
alias cp='cp -i'
alias dir='ls -l'
alias egrep='egrep --color=auto'
alias f='less +F'
alias fgrep='fgrep --color=auto'
alias g='less +G'
alias gerp='grep'
alias grep='grep -i'
alias h='history'
alias j='jobs'
alias l='ls -l'
alias l.='ls -d .* --color=auto'
alias ld='ls -l|grep "^d"'
alias ll='ls -la'
alias ls='ls --color=auto'
alias lr='ls -ltr'
alias mv='mv -i'
alias netstat='ss'
alias p='pwd'
alias rm='rm -i'
alias vo='vi'
alias vu='vi'
alias df='df -h'
alias du='du -h'

LESS='-i -n -q'; export LESS

